# Site settings
title: "Smart Food Inventory: Test Plan Document"

show_downloads: false

remote_theme: "jekyll/minima@bf9ef98"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Navigation settings
# This tells the Minima theme which pages to show in the header.
# The "title" is what users will see.
# The "url" must match the filename of your markdown file (or just "/" for home).
minima:
  skin: classic
  nav_pages:
    - index.md
    - scope.md
    - plan.md
    - phase-01.md
    - phase-02.md
    - phase-03.md
    - validation.md

hide_site_feed_link: true